[workspace]
members = [
  ".",
  "grepa",
]

[package]
name = "repa"
version = "0.1.0"
edition = "2021"

[dependencies]
gcollections = "1.4"
intervallum = "1.3"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
thiserror = "1.0"
once_cell = "1.15"
